### PR TITLE
[IPC] Added correct syscalls for ipc module

### PR DESCRIPTION
**Pull request by SamuelVLC**
The previous syscalls added incorrectly were removed. The correct ones have been in added.
Unit tests yet to be implemented.

### CODE REVIEW

**Comment by SamuelVLC** [comment]
@ppenna there's been an error in one of the checks. can u explain me why?

**Comment by ppenna** [comment]
> @ppenna there's been an error in one of the checks. can u explain me why?

It is failing to build the documentation: https://github.com/nanvix/microkernel/actions/runs/8546724311/job/23417642453

Have you run it locally?

`make TARGET=x86 doxygen`

**Comment by SamuelVLC** [comment]
> > @ppenna there's been an error in one of the checks. can u explain me why?
> 
> It is failing to build the documentation: https://github.com/nanvix/microkernel/actions/runs/8546724311/job/23417642453
> 
> Have you run it locally?
> 
> `make TARGET=x86 doxygen`

I didn't know because I hadn't gotten this error before 😅

**Comment by SamuelVLC** [comment]
@ppenna requested changes in our meeting have been added.

**Comment by ppenna** [comment]
Closing this PR without merge, as I had to rewrite the whole commit history to solve conflicts. Note:
- Before asking for reviews on PRs, rebase it
- Split your PR into multiple commits, each of which buildable and testable.

**Pull request closed without merging**
